global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: "tensorflow"
    scrape_interval: 15s
    metrics_path: /monitoring/prometheus/metrics
    static_configs:
      - targets: ['tf-serving:8500']
